### PR TITLE
Grafana upgrade 2.0.2

### PR DESCRIPTION
**Pull request by mmojana**
In this branch I have migrated grafana to version 2.0.2. These are the most relevant changes:

* Grafana is no more a static site, but a webapp with a proper backend, so:
	* I have configured nginx to pass all the requests form `/` to the appropriate address
	* I have removed elasticsearch as it isn't used anymore for dashboard persistence. This has been replaced with a sqlite DB (can be configured to use other DBs).
	* The dashboard JSON structure is slightly changed, so I have updated the bundled `welcome.json` and `system-metrics.json` files.
	* Grafana is no more configured with a `config.js` file, instead a `custom.ini` file is provided
* The `dashboard-loader.js` script has been heavily changed:
	* It now uses the [Grafana HTTP API](http://docs.grafana.org/reference/http_api/)
	* The script has been moved out of the `grafana/dashboards` folder
	* Directories are now accepted as command line parameters and all the contained files (recursively) will be loaded
	* It's now possible to specify the command line option `-w`, so the files (or directories) specified will be watched for changes. This in my opinion is really handy because the entire `/src/dashboards` directory can be mounted as external volume in docker, so that the dashboards can be added/updated/removed on the fly from outside the container.
	* Removed misused server at the end of the script and adapted the supervisor configuration

I hope you will find my contribution useful and pull it. If you have any suggestion to improve what I have done, please let me know.

### CODE REVIEW

**Comment by ivantopo** [comment]
Hello Marco! Hope you are doing fine :).. man, I just pulled the changes to give them a try and I find that even while the Grafana loads and all, the default welcome dashboard is not available and the system metrics dashboard is there, but it only has random walks.. was that on purpose or maybe I'm missing something?

Overall all the efforts seem to be going in the right direction, we just need to ensure everything is working nicely and then publish a new version of this image, looking forward to your feedback, regards!

**Comment by mmojana** [comment]
Hi Ivan,
I'm fine, thanks. I hope it's the same for you. 
About the two issues you mentioned:

* The default dashboard is not available: grafana seems to have a problem during the insertion of the first dashboard, however in the grafana code the error is not checked, so the API returns a "200 OK" anyway. The problem should be solved by the fix for issue grafana/grafana#1929. What I suspect is that it's related to the fact that when the app is booting the DB is not immediately available. As a workaround, in commit 8ccd87c597269723a297664a42013b1d4017f279 I have added a retry mechanism for the dashboards insertion: when the insert is completed I try to GET it back and if I receive a 404 I repeat the insertion. Is it a valid solution in your opinion?
* The dashboard shows only a random walk: in grafana 2 you can configure one or multiple datasources. By default the only datasource available is a "test datasource" that always provides random walks. If you think it's necessary, I can commit a different config without the "test datasource" and with a graphite datasource that points to the internal installation. Please let me know what you think. Could you please also point me to the toy app you use to test the docker image?

Regards
Marco

**Comment by dpsoft** [comment]
Hello @mmojana ! Hope you are doing fine, Ivan and I we think that is good idea merge you PR and let to the users download the Dashboards from our Site. Can you please update to the Latests Grafana and we are good to go!

**Comment by behrad** [comment]
:+1:

**Comment by mmojana** [comment]
Hi @dpsoft! How are you? I have updated Grafana to 2.1.3 and merged the commits from master. IMHO the grafana API is still not mature and reliable enough, so I had to add a couple of workarounds to cope with the misleading status codes returned. 
The branch is ready to be merged.
Please let me know if I can help you further.

Regards
Marco

**Comment by dpsoft** [comment]
@mmojana  Just need to ask you please squash your commits and amend the message to something like `"Grafana upgrade 2.1.3"` and will merge right away  and we are good to go!

**Comment by mmojana** [comment]
@dpsoft Sorry I'm not a git expert... are my commits "squashed" enough? I had squashed everything in a single commit, but then my branch was behind your master, so I had to pull again and that resulted in another commit. Is it possible/necessary to combine the two commits? Should I just amend the merge commit message so it reads "Grafana upgrade 2.1.3" too? Thank you for the support!

Regards,
Marco

**Comment by dpsoft** [comment]
@mmojana Thanks for Awesome contribution :), hope to see more coming!!!

**Pull request merged**
